---
title: "analysis"
output: html_document
---

```{r loading_libraries, echo=FALSE}
library(dplyr)
library(tidytext)
library(janeaustenr)
library(stringr)
library(ggplot2)
library(gutenbergr)
library(tidyr)
library(scales)
library(ggthemes)
library(magrittr)
library(tidyverse)
library(textdata)
```

```{r gutenberg_corpus_download, echo=FALSE}
louisa <- gutenberg_download(c(28203, 8188, 37106, 2787, 2788, 4770, 38567, 41127, 3795, 2786), mirror = "http://mirrors.xmission.com/gutenberg/", meta_fields = c("title", "author"))
twain <- gutenberg_download(c(3178, 74, 1837, 76, 86, 3179, 102, 91, 93), mirror = "http://mirrors.xmission.com/gutenberg/", meta_fields = c("title", "author"))
```

```{r corpus_creation, echo=FALSE}
louisa_token <- louisa %>%
  group_by(author, title) %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words) %>%
  count(word, sort = FALSE)

twain_token <- twain %>%
  group_by(author, title) %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words) %>%
  count(word, sort = FALSE)
```

```{r lexicon_definition, echo=FALSE}
domestic_words <- c("home","door","bed","knife","window","hall","chair","palace","house","room","table","window","corner","chair","sofa","parlor","wall","supper")
domestic_df <- data.frame(word = domestic_words, domestic = TRUE)
outdoor_words <- c("river","raft","woods","boat","cave","sand","canoe","stream","shore","hill","railroad","steamboat","sea","mud","road","bank","sun","wild","moor","town","carriage","moss","city")
outdoor_df <- data.frame(word = outdoor_words, outdoor = TRUE)
```


```{r tagged_words, echo=TRUE}
twain_tagged <- twain_token %>%
  left_join(domestic_df) %>%
  left_join(outdoor_df)

louisa_tagged <- louisa_token %>%
  left_join(domestic_df) %>%
  left_join(outdoor_df)

write.csv(twain_tagged, "twain.csv")
write.csv(louisa_tagged, "louisa.csv")
```

```{r sentences, echo=TRUE}
twain_sentences <- twain %>%
  group_by(author,title,text) %>%
  summarise (text = paste(text, collapse = "")) %>%
  unnest_regex(sentences, text, pattern = "[.?!]", to_lower = FALSE)

louisa_sentences <- louisa %>%
  group_by(author,title,text) %>%
  summarise (text = paste(text, collapse = "")) %>%
  unnest_regex(sentences, text, pattern = "[.?!]", to_lower = FALSE)
```

```{r sentence_nr, echo=TRUE}
twain_sentence_nr <- twain_sentences %>%
  ungroup() %>%
  mutate(sentence_number = row_number()) %>%
  group_by(author, title, sentence_number) %>%
  unnest_tokens(word, sentences) %>%
  anti_join(stop_words)

louisa_sentence_nr <- louisa_sentences %>%
  ungroup() %>%
  mutate(sentence_number = row_number()) %>%
  group_by(author, title, sentence_number) %>%
  unnest_tokens(word, sentences) %>%
  anti_join(stop_words)
```

```{r concept, echo=TRUE}
twain_concept <- twain_sentence_nr %>%
  left_join(domestic_df) %>%
  left_join(outdoor_df)

louisa_concept <- louisa_sentence_nr %>%
  left_join(domestic_df) %>%
  left_join(outdoor_df)
```

```{r concept_sentiment, echo=TRUE}
twain_concept_sentiment <- twain_concept %>%
  inner_join(get_sentiments("bing"))

louisa_concept_sentiment <- louisa_concept %>%
  inner_join(get_sentiments("bing"))

twain_concept_sentiment_nrc <- twain_concept %>%
  inner_join(get_sentiments("nrc"))

louisa_concept_sentiment_nrc <- louisa_concept %>%
  inner_join(get_sentiments("nrc"))
```

```{r sentiment_total, echo=TRUE}
twain_sentiment_total <- twain_concept_sentiment %>%
  count(sentence_number, sentiment) %>%
  pivot_wider(names_from = sentiment,
              values_from = n,
              values_fill = 0)  %>%
  mutate(sentiment = positive - negative) %>%
  left_join(twain_concept) %>%
  filter(domestic == TRUE | outdoor == TRUE)

louisa_sentiment_total <- louisa_concept_sentiment %>%
  count(sentence_number, sentiment) %>%
  pivot_wider(names_from = sentiment,
              values_from = n,
              values_fill = 0)  %>%
  mutate(sentiment = positive - negative) %>%
  left_join(louisa_concept) %>%
  filter(domestic == TRUE | outdoor == TRUE)
```

```{r sentiment_table, echo=TRUE}
twain_sentiment_table <- twain_sentiment_total %>%
  pivot_longer(domestic:outdoor,
               names_to = "concept",
               values_to = "total_sentiment")  %>%
  drop_na() %>%
  group_by(author, concept) %>%
  summarise (total = sum(sentiment)) %>%
  ungroup()

louisa_sentiment_table <- louisa_sentiment_total %>%
  pivot_longer(domestic:outdoor,
               names_to = "concept",
               values_to = "total_sentiment")  %>%
  drop_na() %>%
  group_by(author, concept) %>%
  summarise (total = sum(sentiment)) %>%
  ungroup()

sentiment_table <- rbind(twain_sentiment_table, louisa_sentiment_table)
```

```{r sentiment_plot, echo=TRUE}
sentiment_table %>%
  ggplot(aes(author, y = total)) +
  geom_col(color = "black",
           alpha = .7,
           position = "identity") +
  facet_wrap(~ concept) +
  labs(title = "Positive and Negative Sentiment by Concept",
       x = "Overal Sentiment",
       y = "Author") +
  coord_flip()
```

```{r sentiment_total, echo=TRUE}
twain_sentiment_total_nrc <- twain_concept_sentiment_nrc %>%
  count(sentence_number, sentiment) %>%
  pivot_wider(names_from = sentiment,
              values_from = n,
              values_fill = 0)  %>%
  #mutate(sentiment = positive + joy + surprise + trust + anticipation - negative - anger - fear - sadness - disgust) %>%
  left_join(twain_concept) %>%
  filter(domestic == TRUE | outdoor == TRUE)

louisa_sentiment_total_nrc <- louisa_concept_sentiment_nrc %>%
  count(sentence_number, sentiment) %>%
  pivot_wider(names_from = sentiment,
              values_from = n,
              values_fill = 0)  %>%
  #mutate(sentiment = positive + joy + surprise + trust + anticipation - negative - anger - fear - sadness - disgust) %>%
  left_join(louisa_concept) %>%
  filter(domestic == TRUE | outdoor == TRUE)
```

```{r sentiment_table, echo=TRUE}
twain_sentiment_table_nrc <- twain_sentiment_total_nrc %>%
  pivot_longer(domestic:outdoor,
               names_to = "concept",
               values_to = "total_sentiment")  %>%
  drop_na() %>%
  group_by(author, concept) %>%
  summarise (total = sum(sentiment)) %>%
  ungroup()

louisa_sentiment_table_nrc <- louisa_sentiment_total_nrc %>%
  pivot_longer(domestic:outdoor,
               names_to = "concept",
               values_to = "total_sentiment")  %>%
  drop_na() %>%
  group_by(author, concept) %>%
  summarise (total = sum(sentiment)) %>%
  ungroup()

sentiment_table <- rbind(twain_sentiment_table_nrc, louisa_sentiment_table_nrc)
```

```{r sentiment_plot, echo=TRUE}
sentiment_table %>%
  ggplot(aes(author, y = total)) +
  geom_col(color = "black",
           alpha = .7,
           position = "identity") +
  facet_wrap(~ concept) +
  labs(title = "Positive and Negative Sentiment by Concept",
       x = "Positive Sentiment",
       y = "Author") +
  coord_flip()
```